# RuboCop configuration
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

# Disable documentation requirements for now
Style/Documentation:
  Enabled: false

# Increase limits for method and class length
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'app/controllers/api/v1/documents_controller.rb#add_editors'
    - 'app/models/document.rb#version_history'
    - 'db/migrate/**/*.rb'

Metrics/ClassLength:
  Max: 150

# Increase limits for complexity
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'app/models/document.rb#version_history'
    - 'db/migrate/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 10

# Increase parameter list limit
Metrics/ParameterLists:
  Max: 7

# Increase line length limit
Layout/LineLength:
  Max: 150
  Exclude:
    - 'config/initializers/devise.rb'

# Increase block length limit
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'db/schema.rb'

# Allow non-local exits in iterators for controllers
Lint/NonLocalExitFromIterator:
  Enabled: false

# Allow constant definition in blocks for initializers
Lint/ConstantDefinitionInBlock:
  Enabled: false

# Skip hash-like case for active storage initializer
Style/HashLikeCase:
  Exclude:
    - 'config/initializers/active_storage.rb'