:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:queues:
  - [default, 1]
  - [mailers, 2]
  - [active_storage, 2]

:max_retries: 3
:retry_interval: 5

# Redis configuration - prioritize REDISCLOUD_URL for production
:redis_url: <%= ENV.fetch("REDIS_URL") { ENV.fetch("REDIS_URL", "redis://localhost:6379/0") } %>
